sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: your password
  alioss:
    access-key-id: your own key
    endpoint: your end point
    access-key-secret: your key
    bucket-name: your buck name
  redis:
    port: 6379
    password: 123456
    host: localhost
    database: 1
  wechat:
    appid: your wechat appid
    secret: your secret
  shop:
    address: 北京市海淀区上地街10号
  baidu:
    ak: your baidu ak
